apiVersion: v1
kind: pod
metadata:
  labels:
    project: roboshop
    environment: dev
  annotations:
    iamgeregistry: "https://hub.docker.com/"
    jenkinsbuildurl: "https://jenkins.joindevops.com/build/roboshop/job/2"
spec:
  containers:
  - name: nginx
  - image: nginx
